<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="InputPort\**" />
    <Compile Remove="Interactors\**" />
    <Compile Remove="NewFolder\**" />
    <Compile Remove="OutputPort\**" />
    <EmbeddedResource Remove="InputPort\**" />
    <EmbeddedResource Remove="Interactors\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <EmbeddedResource Remove="OutputPort\**" />
    <None Remove="InputPort\**" />
    <None Remove="Interactors\**" />
    <None Remove="NewFolder\**" />
    <None Remove="OutputPort\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AeroMexic.Domain\AeroMexic.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

</Project>
